from tkinter import *
import mysql.connector as mc
import random 
from datetime import datetime
from tkinter import messagebox
from Logger import *
def fir(userid):
    log('inside FIR function:  REGISTER COMPLAINT Button was clicked')
    master=Tk()
    Centerlbl=Label(master,text="FIR DETAILS").pack()
    rand=random.randint(1,100)
    FIRframe=Frame(master)
    FIRframe.pack(pady=50,padx=100)
    today = datetime.now()
    casenumber=today.strftime("%d%m%y")+str(rand)
    casenumber=int(casenumber)
    log('new case number generated is:',casenumber,type(casenumber))
    
    cnamlbl=Label(FIRframe,text="complainant name")
    cnamtxt=Entry(FIRframe)
    c_phonelbl=Label(FIRframe,text="complainant phone number")
    c_phonetxt=Entry(FIRframe)
    datelbl=Label(FIRframe,text="date of incident")
    datetxt=Entry(FIRframe)
    timelbl=Label(FIRframe,text="time of incident")
    timetxt=Entry(FIRframe)
    caddlbl=Label(FIRframe,text="complainant address")
    caddtxt=Entry(FIRframe)
    ctylbl=Label(FIRframe,text="case type")
    ctytxt=Entry(FIRframe)
    deslbl=Label(FIRframe,text="description of the case")
    destxt=Entry(FIRframe)
    suspectlbl=Label(FIRframe,text="suspect name(*if any)")
    suspecttxt=Entry(FIRframe)
    localitylbl=Label(FIRframe,text="name of the locality")
    localitytxt=Entry(FIRframe)
    stlbl=Label(FIRframe,text="name of the state")
    sttxt=Entry(FIRframe)
    mycon=mc.connect(host="localhost",user="root",passwd="",database="user")
    cur=mycon.cursor()
    
    def submit():
        can_name=cnamtxt.get()
        datein=datetxt.get()
        timein=timetxt.get()
        caddress=caddtxt.get()
        ctype=ctytxt.get()
        description=destxt.get()
        casestatus='New Case'
        name_of_suspect=suspecttxt.get()
        locality=localitytxt.get()
        state=sttxt.get()
        phonenum=c_phonetxt.get()
        log('values entered by user',can_name,datein,timein,caddress,ctype,description)
        st="insert into cases values({},'{}','{}','{}','{}','{}','{}','{}','{}','{}','{}','{}','{}')".format(casenumber,can_name,phonenum,datein,timein,caddress,ctype,description,casestatus,name_of_suspect,locality,state,userid)
        log(st)
        cur.execute(st)
        cur.execute("commit;")
        log('FIR entered in Db successfully')
        messagebox.showinfo("Complaint Registered","Your complaint has been accepted and added to DB\n the complaint no is: "+str(casenumber))
        master.destroy()
        #end of submit function
    def destroy():
        master.destroy()
    cnamtxt.place(relx=1.5,rely=1.7,anchor=CENTER)
    cnamlbl.grid(row=1,column=1)
    cnamtxt.grid(row=1,column=3)
    c_phonelbl.grid(row=3,column=1)
    c_phonetxt.grid(row=3,column=3)
    datelbl.grid(row=5,column=1)
    datetxt.grid(row=5,column=3)
    timelbl.grid(row=7,column=1)
    timetxt.grid(row=7,column=3)
    caddlbl.grid(row=9,column=1)
    caddtxt.grid(row=9,column=3)
    ctylbl.grid(row=11,column=1)
    ctytxt.grid(row=11,column=3)
    deslbl.grid(row=13,column=1)
    destxt.grid(row=13,column=3)
    suspectlbl.grid(row=17,column=1)
    suspecttxt.grid(row=17,column=3)
    localitylbl.grid(row=19,column=1)
    localitytxt.grid(row=19,column=3)
    stlbl.grid(row=21,column=1)
    sttxt.grid(row=21,column=3)
    butt=Button(FIRframe,text="submit",command=submit).grid(row=23,column=1)
    butt2=Button(FIRframe,text="go back",command=destroy).grid(row=23,column=3)
    master.mainloop()


